major_frame: 1s
partitions:
  - id: 1
    name: Echo
    duration: 100ms
    offset: 0ms
    period: 1s
    image: target/x86_64-unknown-linux-musl/release/echo
  - id: 2
    name: Network
    duration: 100ms
    offset: 500ms
    period: 1s
    image: target/x86_64-unknown-linux-musl/release/np-client
    udp_ports:
      - "127.0.0.1:34254"
channel:
  - !Sampling
    name: EchoRequest
    msg_size: 100B
    source: Echo
    destination:
      - Network
  - !Sampling
    name: EchoReply
    msg_size: 100B
    source: Network
    destination:
      - Echo
