major_frame: 100ms
partitions:
  - id: 0
    name: Echo
    duration: 50ms
    offset: 50ms
    period: 100ms
    image: target/x86_64-unknown-linux-musl/release/echo-server
  - id: 1
    name: Network
    duration: 50ms
    offset: 0s
    period: 100ms
    image: target/x86_64-unknown-linux-musl/release/np-server
    udp_ports:
      - "127.0.0.1:34256"
channel:
  - !Sampling
    name: EchoRequest
    msg_size: 100B
    source: Network
    destination:
      - Echo
  - !Sampling
    name: EchoReply
    msg_size: 100B
    source: Echo
    destination:
      - Network
