stack_size:
  aperiodic_process: 1MB
virtual_links:
  - id: 1
    msg_size: 100B
    ports:      
      - !SamplingPortSource
        channel: EchoRequest
  - id: 2
    msg_size: 100B
    interfaces: [ "34256" ]
    ports:
      - !SamplingPortDestination
        channel: EchoReply
        validity: 4s
interfaces:
  - !Udp
    id: 1
    name: "34256"
    rate: 10000000
    mtu: 1.5KB
    source: "127.0.0.1:34256"
    destination: "127.0.0.1:34254"
schedule:
  !DeadlineRr
  slots:
    - vl: 1
      period: 200ms
    - vl: 2
      period: 200ms
