stack_size:
  aperiodic_process: 15000
virtual_links:
  - id: 1
    msg_size: 100
    fifo_depth: 10
    interfaces: [ ]
    ports:
      - !QueuingPortReceiver
        channel: EchoRequestCl
      - !QueuingPortSender
        channel: EchoRequestSrv
  - id: 2
    msg_size: 100
    fifo_depth: 10
    interfaces: [ ]
    ports:
      - !QueuingPortReceiver
        channel: EchoReplySrv
      - !QueuingPortSender
        channel: EchoReplyCl
schedule:
  !DeadlineRr
  slots:
    - vl: 1
      period: 50us
    - vl: 2
      period: 50us
