stack_size:
  aperiodic_process: 32768
virtual_links:
  - id: 1
    msg_size: 8192
    interfaces: [ "uart0" ]
    fifo_depth: 256
    ports:
      - !QueuingPortReceiver
        channel: "TrafficSN"
interfaces:
  - !Uart
    id: 1
    mtu: 8192
    name: "uart0"
schedule:
  !DeadlineRr
  slots:
    - vl: 1
      # This is ca the effective data rate of the UART.
      period: 572ms
