stack_size:
  aperiodic_process: 15000
virtual_links:
  - id: 2
    msg_size: 100
    interfaces: [ "uart0" ]
    fifo_depth: 10
    ports:
      - !QueuingPortReceiver
        channel: EchoReplySrv
  - id: 1
    msg_size: 100
    fifo_depth: 10
    ports:
      - !QueuingPortSender
        channel: EchoRequestSrv
interfaces:
  - !Uart
    id: 1
    name: "uart0"
    mtu: 1500
schedule:
  !DeadlineRr
  slots:
    - vl: 1
      period: 7ms
    - vl: 2
      period: 7ms
