stack_size:
  aperiodic_process: 32768B
virtual_links:
  - id: 1
    msg_size: 8192
    interfaces: [ ]
    fifo_depth: 256
    ports:
      - !QueuingPortSender
        channel: TrafficRN
schedule:
  !DeadlineRr
  slots:
    - vl: 1
      period: 10ms
interfaces:
  - !Uart
    id: 1
    name: "uart0"
    mtu: 8192
