stack_size:
  aperiodic_process: 25KB
virtual_links:
  - id: 1
    msg_size: 8192
    interfaces: [ ]
    fifo_depth: 256
    ports:
      - !QueuingPortReceiver
        channel: TrafficSN
      - !QueuingPortSender
        channel: TrafficRN
schedule:
  !DeadlineRr
  slots:
    - vl: 1
      period: 40us
